# Generated by Django 5.1.5 on 2025-02-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produto',
            table='catalogo_produto',
        ),
    ]
