# Generated by Django 5.1.5 on 2025-02-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_produto_desconto_alter_produto_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='link',
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
