# Generated by Django 5.1.5 on 2025-02-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_remove_produto_desconto_remove_produto_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='frete_gratis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='parcelamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='percentual_desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_sem_desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_entrega',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
